[package]
name = "rust-sudoku"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.3.25"
egui-macroquad = "0.15.0"

[profile.release]
strip = true
opt-level = 3

[profile.dev.package.'*']
opt-level = 3